name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

    - run: find . -name \*apk

    - uses: actions/upload-artifact@v2
      with:
        name: Corona-Warn-App-device-release-unsigned
        path: Corona-Warn-App/build/outputs/apk/device/release/Corona-Warn-App-device-release-unsigned.apk
    - uses: actions/upload-artifact@v2
      with:
        name: Corona-Warn-App-device-debug
        path: Corona-Warn-App/build/outputs/apk/device/debug/Corona-Warn-App-device-debug.apk
        
